### ISSUE TITLE
Session Garbage Collection and Other issues

### ISSUE THREAD

**Issue by CMCDragonkai** [shabbyrobe/cachet#4]
If I used your library to implement as backing to sessions, and I used something like File backend, what would be your suggested solution to garbage collection?

Is there a way to suppress the warning that you said would be raised?

Also does cachet prevent me from using the memory backend for sessions too? I know that it doesn't get persisted across requests, but I have a special requirement.

**Comment by shabbyrobe** [comment]
> If I used your library to implement as backing to sessions, and I used something like File backend, what would be your suggested solution to garbage collection?

Some kind of server process would be best, i.e. a cron job. But the `Cachet\SessionHandler` class does implement the `gc` method, so if you want Cachet to handle it for you, you can pass an option to `Cachet\SessionHandler::register()` like so:
```php
Cachet\SessionHandler::register($cache, ['runGc'=>true]);
```

Just as with regular PHP sessions backed by the default mechanism, this can cause some nasty "stop-the-world" headaches if you have a lot of sessions, hence why Debian distributions disable the session GC feature in `php.ini` and implement their own cron-based solution, which is what I recommend you do as well for backends that don't support automatic invalidation based on a TTL.

> Is there a way to suppress the warning that you said would be raised?

Yep! Use the `@` operator before the call to `register`:
```php
$backend = new Cachet\Backend\File('/tmp');
$cache = new Cachet\Cache('test', $backend);
@Cachet\SessionHandler::register($cache);
```
 
> Also does cachet prevent me from using the memory backend for sessions too? I know that it doesn't get persisted across requests, but I have a special requirement.

It won't stop you from using the Memory backend, but you won't see values in the backend until the script is shutting down, which is when PHP actually calls the `SessionHandler` methods:
```php
$backend = new Cachet\Backend\Memory;
$cache = new Cachet\Cache('test', $backend);
Cachet\SessionHandler::register($cache);

session_start();
$_SESSION['foo'] = 'bar';
var_dump($_SESSION);
var_dump($backend); // nothing here!
```

**Comment by shabbyrobe** [comment]
Do you mind if I ask you what your special requirements are?

**Comment by CMCDragonkai** [comment]
I was creating an auth library that can be usable for both daemons (long running processes) and non-daemons (standard php lifecycle). For long running processes, session data may just persist in memory for a period of time.

**Comment by shabbyrobe** [comment]
Was the solution proposed in my previous answer adequate?

**Comment by shabbyrobe** [comment]
Closed due to inactivity.
