### ISSUE TITLE
Redis delete is "soft deprecated"

### ISSUE THREAD

**Issue by TuningYourCode** [shabbyrobe/cachet#9]
php-redis 5+ onwards the delete call is "soft deprecated" and only an alias to "del"-call.

The "del"-call should be at least avaible since version 2.1.0 of php-redis extentsion. Debian oldstable (stretch) currently has version 3.1.1.

See:
https://github.com/phpredis/phpredis/blob/develop/Changelog.md#deprecated

**Comment by TuningYourCode** [comment]
@shabbyrobe can you checkout the build error (because of mysql connection error) or isn't that related to releasing of version 3.0.1 to packagist ?

**Comment by shabbyrobe** [comment]
I'll take a look now. This is just from running a "composer require"?

**Comment by shabbyrobe** [comment]
Oh, sorry, travis build error. That doesn't look related to your changes. I'll see if I can unstick it.

**Comment by shabbyrobe** [comment]
Fixed!

**Comment by TuningYourCode** [comment]
Thx for your fast approval and fixes to travis :)

**Comment by shabbyrobe** [comment]
No worries, thank you for the fix! Your timing was incredible, I had basically opened up github the second you reported the issue :)
